class Chest extends ManPart {
	
	constructor(options) {
		options.img = 'manChest';
		super(options);
	}
	
	static make(options) {
		const info = [
			{enum: 0, name: '', index: new QQ.Point(0, 0)},
			{enum: 1, name: '', index: new QQ.Point(1, 0)},
			{enum: 2, name: '', index: new QQ.Point(2, 0)},
			{enum: 3, name: '', index: new QQ.Point(3, 0)},
			{enum: 4, name: '', index: new QQ.Point(0, 1)},
			{enum: 5, name: '', index: new QQ.Point(1, 1)},
			{enum: 6, name: '', index: new QQ.Point(2, 1)},
			{enum: 7, name: '', index: new QQ.Point(3, 1)},
			{enum: 8, name: '', index: new QQ.Point(0, 2)},
			{enum: 9, name: '', index: new QQ.Point(1, 2)},
			{enum: 10, name: '', index: new QQ.Point(2, 2)},
			{enum: 11, name: '', index: new QQ.Point(3, 2)},
			{enum: 12, name: '', index: new QQ.Point(0, 3)},
			{enum: 13, name: '', index: new QQ.Point(1, 3)},
			{enum: 14, name: '', index: new QQ.Point(2, 3)},
			{enum: 15, name: '', index: new QQ.Point(3, 3)},
			{enum: 16, name: '', index: new QQ.Point(0, 4)},
			{enum: 17, name: '', index: new QQ.Point(1, 4)},
			{enum: 18, name: '', index: new QQ.Point(2, 4)},
			{enum: 19, name: '', index: new QQ.Point(3, 4)},
			{enum: 20, name: '', index: new QQ.Point(0, 5)},
			{enum: 21, name: '', index: new QQ.Point(1, 5)},
			{enum: 22, name: '', index: new QQ.Point(2, 5)},
			{enum: 23, name: '', index: new QQ.Point(3, 5)},
			{enum: 24, name: '', index: new QQ.Point(0, 6)},
			{enum: 25, name: '', index: new QQ.Point(1, 6)},
			{enum: 26, name: '', index: new QQ.Point(2, 6)},
			{enum: 27, name: '', index: new QQ.Point(3, 6)},
			{enum: 28, name: '', index: new QQ.Point(0, 7)},
			{enum: 29, name: '', index: new QQ.Point(1, 7)},
			{enum: 30, name: '', index: new QQ.Point(2, 7)},
			{enum: 31, name: '', index: new QQ.Point(3, 7)},
			{enum: 32, name: '', index: new QQ.Point(0, 8)},
			{enum: 33, name: '', index: new QQ.Point(1, 8)},
			{enum: 34, name: '', index: new QQ.Point(2, 8)},
			{enum: 35, name: '', index: new QQ.Point(3, 8)},
			{enum: 36, name: '', index: new QQ.Point(0, 9)},
			{enum: 37, name: '', index: new QQ.Point(1, 9)},
			{enum: 38, name: '', index: new QQ.Point(2, 9)},
			{enum: 39, name: '', index: new QQ.Point(3, 9)},
			{enum: 40, name: '', index: new QQ.Point(4, 5)},
			{enum: 41, name: '', index: new QQ.Point(5, 5)},
			{enum: 42, name: '', index: new QQ.Point(6, 5)},
			{enum: 43, name: '', index: new QQ.Point(7, 5)},
			{enum: 44, name: '', index: new QQ.Point(4, 6)},
			{enum: 45, name: '', index: new QQ.Point(5, 6)},
			{enum: 46, name: '', index: new QQ.Point(6, 6)},
			{enum: 47, name: '', index: new QQ.Point(7, 6)},
			{enum: 48, name: '', index: new QQ.Point(4, 7)},
			{enum: 49, name: '', index: new QQ.Point(5, 7)},
			{enum: 50, name: '', index: new QQ.Point(6, 7)},
			{enum: 51, name: '', index: new QQ.Point(7, 7)},
			{enum: 52, name: '', index: new QQ.Point(4, 8)},
			{enum: 53, name: '', index: new QQ.Point(5, 8)},
			{enum: 54, name: '', index: new QQ.Point(6, 8)},
			{enum: 55, name: '', index: new QQ.Point(7, 8)},
			{enum: 56, name: '', index: new QQ.Point(4, 9)},
			{enum: 57, name: '', index: new QQ.Point(5, 9)},
			{enum: 58, name: '', index: new QQ.Point(6, 9)},
			{enum: 59, name: '', index: new QQ.Point(7, 9)},
			{enum: 60, name: '', index: new QQ.Point(4, 0)},
			{enum: 61, name: '', index: new QQ.Point(5, 0)},
			{enum: 62, name: '', index: new QQ.Point(6, 0)},
			{enum: 63, name: '', index: new QQ.Point(7, 0)},
			{enum: 64, name: '', index: new QQ.Point(4, 1)},
			{enum: 65, name: '', index: new QQ.Point(5, 1)},
			{enum: 66, name: '', index: new QQ.Point(6, 1)},
			{enum: 67, name: '', index: new QQ.Point(7, 1)},
			{enum: 68, name: '', index: new QQ.Point(4, 2)},
			{enum: 69, name: '', index: new QQ.Point(5, 2)},
			{enum: 70, name: '', index: new QQ.Point(6, 2)},
			{enum: 71, name: '', index: new QQ.Point(7, 2)},
			{enum: 72, name: '', index: new QQ.Point(4, 3)},
			{enum: 73, name: '', index: new QQ.Point(5, 3)},
			{enum: 74, name: '', index: new QQ.Point(6, 3)},
			{enum: 75, name: '', index: new QQ.Point(7, 3)},
			{enum: 76, name: '', index: new QQ.Point(4, 4)},
			{enum: 77, name: '', index: new QQ.Point(5, 4)},
			{enum: 78, name: '', index: new QQ.Point(6, 4)},
			{enum: 79, name: '', index: new QQ.Point(7, 4)},
			{enum: 80, name: '', index: new QQ.Point(8, 0)},
			{enum: 81, name: '', index: new QQ.Point(9, 0)},
			{enum: 82, name: '', index: new QQ.Point(10, 0)},
			{enum: 83, name: '', index: new QQ.Point(11, 0)},
			{enum: 84, name: '', index: new QQ.Point(8, 1)},
			{enum: 85, name: '', index: new QQ.Point(9, 1)},
			{enum: 86, name: '', index: new QQ.Point(10, 1)},
			{enum: 87, name: '', index: new QQ.Point(11, 1)},
			{enum: 88, name: '', index: new QQ.Point(8, 2)},
			{enum: 89, name: '', index: new QQ.Point(9, 2)},
			{enum: 90, name: '', index: new QQ.Point(10, 2)},
			{enum: 91, name: '', index: new QQ.Point(11, 2)},
			{enum: 92, name: '', index: new QQ.Point(8, 3)},
			{enum: 93, name: '', index: new QQ.Point(9, 3)},
			{enum: 94, name: '', index: new QQ.Point(10, 3)},
			{enum: 95, name: '', index: new QQ.Point(11, 3)},
			{enum: 96, name: '', index: new QQ.Point(8, 4)},
			{enum: 97, name: '', index: new QQ.Point(9, 4)},
			{enum: 98, name: '', index: new QQ.Point(10, 4)},
			{enum: 99, name: '', index: new QQ.Point(11, 4)},
			{enum: 100, name: '', index: new QQ.Point(8, 5)},
			{enum: 101, name: '', index: new QQ.Point(9, 5)},
			{enum: 102, name: '', index: new QQ.Point(10, 5)},
			{enum: 103, name: '', index: new QQ.Point(11, 5)},
			{enum: 104, name: '', index: new QQ.Point(8, 6)},
			{enum: 105, name: '', index: new QQ.Point(9, 6)},
			{enum: 106, name: '', index: new QQ.Point(10, 6)},
			{enum: 107, name: '', index: new QQ.Point(11, 6)},
			{enum: 108, name: '', index: new QQ.Point(8, 7)},
			{enum: 109, name: '', index: new QQ.Point(9, 7)},
			{enum: 110, name: '', index: new QQ.Point(10, 7)},
			{enum: 111, name: '', index: new QQ.Point(11, 7)},
			{enum: 112, name: '', index: new QQ.Point(8, 8)},
			{enum: 113, name: '', index: new QQ.Point(9, 8)},
			{enum: 114, name: '', index: new QQ.Point(10, 8)},
			{enum: 115, name: '', index: new QQ.Point(11, 8)},
			{enum: 116, name: '', index: new QQ.Point(8, 9)},
			{enum: 117, name: '', index: new QQ.Point(9, 9)},
			{enum: 118, name: '', index: new QQ.Point(10, 9)},
			{enum: 119, name: '', index: new QQ.Point(11, 9)}
		];
		ManPart.setEnumForEnemy(options, info);
		if ( ManPart.fillInfo(info, options) ) {
			return new Chest(options);
		}
		return null;
	}
	
};
